// {
//       invoice: {
//         can_send_in_mail: false,
//         submitted_by_email: '',
//         bcy_shipping_charge_tax: '',
//         gst_no: '',
//         tax_reg_no: '',
//         is_eway_bill_required: false,
//         tax_specification: 'inter',
//         stop_reminder_until_payment_expected_date: false,
//         customer_default_billing_address: {
//           zip: '462016',
//           country: 'India',
//           address: 'mx 175 e7 extension Arera colony',
//           city: 'BHOPAL - BPA',
//           phone: '09131968397',
//           street2: 'mx 175 e7 extension Arera colony',
//           state: 'Madhya Pradesh',
//           fax: '',
//           state_code: ''
//         },
//         inprocess_transaction_present: false,
//         submitted_date_formatted: '',
//         estimate_id: '',
//         customer_custom_fields: [],
//         status_formatted: 'Draft',
//         shipping_charge_tax_id: '',
//         ecomm_operator_name: '',
//         is_autobill_enabled: false,
//         tax_treatment_formatted: 'Consumer',
//         shipping_charge_tax_name: '',
//         discount_total: 0,
//         tax_total: 396.66,
//         write_off_amount: 0,
//         is_viewed_by_client: false,
//         salesorder_id: '',
//         merchant_gst_no: '',
//         sub_statuses: [],
//         last_reminder_sent_date_formatted: '',
//         client_viewed_time_formatted: '',
//         email: '',
//         reason_for_debit_note: 'others',
//         salesorders: [],
//         adjustment_description: 'transport charges',
//         currency_symbol: '₹',
//         gst_treatment_formatted: 'Consumer',
//         ach_supported: false,
//         shipping_bills: [],
//         type_formatted: 'Tax Invoice',
//         transaction_rounding_type: 'no_rounding',
//         roundoff_value: 0,
//         contact_persons_details: [],
//         template_name: 'Spreadsheet Template',
//         salesorder_number: '',
//         template_id: '1155413000000015130',
//         customer_name: ' B.Pradeep kumar',
//         total_formatted: '₹2,601.00',
//         discount_total_formatted: '₹0.00',
//         payment_terms_label: 'Due on Receipt',
//         is_reverse_charge_applied: false,
//         show_no_of_copies: false,
//         notes: '',
//         documents: [],
//         client_viewed_time: '',
//         ecomm_operator_id: '',
//         tds_override_preference: 'no_override',
//         shipping_charge_inclusive_of_tax: 0,
//         contact: {
//           is_credit_limit_migration_completed: false,
//           unused_customer_credits_formatted: '₹0.00',
//           credit_limit_formatted: '₹0.00',
//           customer_balance_formatted: '₹0.00',
//           unused_customer_credits: 0,
//           credit_limit: 0,
//           customer_balance: 0
//         },
//         payment_discount_formatted: '₹0.00',
//         invoice_id: '1155413000068524104',
//         contact_category: 'consumer',
//         template_type: 'excel',
//         recurring_invoice_id: '',
//         can_send_invoice_sms: true,
//         contact_persons: [],
//         shipping_charge_tax: '',
//         gst_treatment: 'consumer',
//         created_time: '2024-03-23T16:33:19+0530',
//         created_date_formatted: '23/03/2024',
//         is_inclusive_tax: true,
//         reference_invoice: { reference_invoice_id: '' },
//         price_precision: 2,
//         sub_total_inclusive_of_tax_formatted: '₹0.00',
//         submitted_by_photo_url: '',
//         tax_treatment: 'consumer',
//         payment_discount: 0,
//         approvers_list: [],
//         shipping_charge_tax_percentage: '',
//         zcrm_potential_name: '',
//         adjustment: 0,
//         filed_in_vat_return_name: '',
//         current_sub_status: 'draft',
//         due_date_formatted: '23/03/2024',
//         shipping_charge_inclusive_of_tax_formatted: '₹0.00',
//         merchant_id: '',
//         gst_return_details: {
//           status_formatted: '',
//           return_period: '',
//           status: '',
//           return_period_formatted: ''
//         },
//         invoice_source: 'Client',
//         shipping_charge_exclusive_of_tax_formatted: '₹0.00',
//         current_sub_status_id: '',
//         custom_field_hash: {
//           cf_payment_to_be_collected_if_: '0',
//           cf_payment_to_be_collected_if__unformatted: '0',
//           cf_terms_of_payment: 'Cash on Delivery',
//           cf_sales_account: "Other's Sales",
//           cf_sales_account_unformatted: "Other's Sales",
//           cf_terms_of_payment_unformatted: 'Cash on Delivery'
//         },
//         tax_amount_withheld: 0,
//         qr_code: {
//           qr_source: 'invoice_url',
//           is_qr_enabled: true,
//           qr_value: '',
//           qr_description: 'Scan the QR code to view the configured information.'
//         },
//         ewaybills: [],
//         next_reminder_date_formatted: '',
//         shipping_charge_tax_type: '',
//         subject_content: '',
//         payment_expected_date: '',
//         is_emailed: false,
//         unused_retainer_payments: 0,
//         offline_created_date_with_time: '',
//         shipping_charge: 0,
//         bcy_adjustment: 0,
//         allow_partial_payments: false,
//         customer_custom_field_hash: {},
//         ecomm_operator_gst_no: '',
//         currency_id: '1155413000000000064',
//         includes_package_tracking_info: false,
//         zcrm_potential_id: '',
//         place_of_supply: 'AD',
//         discount: 0,
//         taxes: [ [Object], [Object] ],
//         is_client_review_settings_enabled: false,
//         billing_address: {
//           zip: '462016',
//           country: 'India',
//           address: 'mx 175 e7 extension Arera colony',
//           city: 'BHOPAL - BPA',
//           phone: '09131968397',
//           street: 'mx 175 e7 extension Arera colony',
//           attention: '',
//           street2: 'mx 175 e7 extension Arera colony',
//           state: 'Madhya Pradesh',
//           fax: ''
//         },
//         line_items: [
// {
// line_item_id: '1155413000068986063',
// documents: [],
// discount_amount: 0,
// item_type: 'inventory',
// item_type_formatted: 'Inventory Items',
// discount: 0,
// internal_name: '',
// sales_rate_formatted: '₹1.00',
// discounts: [],
// project_id: '',
// sku: 'K - 1200',
// pricing_scheme: 'unit',
// pricebook_id: '',
// bill_id: '',
// bcy_rate_formatted: '₹1.00',
// image_document_id: '',
// expense_receipt_name: '',
// item_total: 1,
// tax_id: '1155413000000062172',
// tags: [],
// unit: 'pcs',
// warehouse_name: 'Katyayani Organics',
// cost_amount: 0,
// tax_type: 'tax',
// time_entry_ids: [],
// cost_amount_formatted: '₹0.00',
// name: 'Humic Acid 1 KG',
// markup_percent_formatted: '0.00%',
// discount_amount_formatted: '₹0.00',
// bcy_rate: 1,
// item_total_formatted: '₹1.00',
// is_combo_product: false,
// salesorder_item_id: '',
// rate_formatted: '₹1.00',
// has_product_type_mismatch: false,
// header_id: '',
// description: '',
// gst_treatment_code: '',
// item_order: 1,
// bill_item_id: '',
// rate: 1,
// account_name: 'In-house Sales',
// hsn_or_sac: '310510',
// package_details: {
// weight_unit: 'kg',
// length: '',
// width: '',
// weight: '',
// dimension_unit: 'cm',
// height: ''
// },
// sales_rate: 1,
// quantity: 1,
// item_id: '1155413000017419069',
// reverse_charge_tax_id: '',
// tax_name: 'IGST5',
// header_name: '',
// item_custom_fields: [[Object]],
// line_item_taxes: [[Object]],
// markup_percent: 0,
// product_type: 'goods',
// account_id: '1155413000000000486',
// tax_percentage: 5,
// expense_id: '',
// has_invalid_hsn: false,
// warehouse_id: '1155413000000081002'
// },
// {
// line_item_id: '1155413000068986065',
// documents: [],
// discount_amount: 0,
// item_type: 'sales',
// item_type_formatted: 'Sales Items (Service)',
// discount: 0,
// internal_name: '',
// sales_rate_formatted: '₹160.00',
// discounts: [],
// project_id: '',
// sku: '',
// pricing_scheme: 'unit',
// pricebook_id: '',
// bill_id: '',
// bcy_rate_formatted: '₹160.00',
// image_document_id: '',
// expense_receipt_name: '',
// item_total: 160,
// tax_id: '1155413000000062176',
// tags: [],
// unit: '',
// cost_amount: 0,
// tax_type: 'tax',
// time_entry_ids: [],
// cost_amount_formatted: '₹0.00',
// name: 'Bio NPK 1000 ML',
// markup_percent_formatted: '0.00%',
// discount_amount_formatted: '₹0.00',
// bcy_rate: 160,
// item_total_formatted: '₹160.00',
// is_combo_product: false,
// salesorder_item_id: '',
// rate_formatted: '₹160.00',
// has_product_type_mismatch: false,
// header_id: '',
// description: '',
// gst_treatment_code: '',
// item_order: 2,
// bill_item_id: '',
// rate: 160,
// account_name: 'In-house Sales',
// hsn_or_sac: '123456',
// package_details: {
// weight_unit: 'kg',
// length: '',
// width: '',
// weight: '',
// dimension_unit: 'cm',
// height: ''
// },
// sales_rate: 160,
// quantity: 1,
// item_id: '1155413000025166213',
// reverse_charge_tax_id: '',
// tax_name: 'IGST18',
// header_name: '',
// item_custom_fields: [],
// line_item_taxes: [[Object]],
// markup_percent: 0,
// product_type: 'service',
// account_id: '1155413000000000486',
// tax_percentage: 18,
// expense_id: '',
// has_invalid_hsn: false
// }
// ],
//         type: 'invoice',
//         payment_expected_date_formatted: '',
//         balance: 2601,
//         terms: 'We Declare that this invoice shows the actual price of the goods described and that all particular are true and correct\n' +
//           '\n' +
//           '                                              SUBJECTED TO BHOPAL JURISDICTION',
//         credits_applied: 0,
//         picklists: [],
//         credits_applied_formatted: '₹0.00',
//         filed_in_vat_return_id: '',
//         invoice_number: 'test456',
//         payment_options: { payment_gateways: [Array] },
//         debit_notes: [],
//         sub_total_inclusive_of_tax: 0,
//         exchange_rate: 1,
//         invoice_source_formatted: 'Client',
//         approver_id: '',
//         merchant_name: '',
//         sales_channel: 'direct_sales',
//         shipping_charge_formatted: '₹0.00',
//         reference_number: '',
//         reverse_charge_tax_total_formatted: '₹0.00',
//         discount_percent: 0,
//         is_pre_gst: false,
//         page_height: '11.69in',
//         status: 'draft',
//         reader_offline_payment_initiated: false,
//         schedule_time_formatted: '',
//         adjustment_formatted: '₹0.00',
//         balance_formatted: '₹2,601.00',
//         dispatch_from_address: {},
//         currency_code: 'INR',
//         page_width: '8.27in',
//         bcy_total: 2601,
//         date_formatted: '23/03/2024',
//         tax_rounding: 'entity_level',
//         last_modified_time: '2024-03-23T16:33:19+0530',
//         discount_type: 'item_level',
//         deliverychallans: [],
//         schedule_time: '',
//         customer_id: '1155413000016637106',
//         roundoff_value_formatted: '₹0.00',
//         unused_retainer_payments_formatted: '₹0.00',
//         is_taxable: true,
//         date: '2024-03-23',
//         submitted_date: '',
//         template_type_formatted: 'Spreadsheet',
//         can_generate_ewaybill_using_irn: true,
//         currency_name_formatted: 'INR- Indian Rupee',
//         created_by_name: 'Katyayani Manager',
//         tds_summary: [],
//         reference_invoice_type: '',
//         last_modified_by_id: '1155413000000015001',
//         write_off_amount_formatted: '₹0.00',
//         shipping_charge_tax_exemption_code: '',
//         color_code: '',
//         bcy_tax_total: 396.66,
//         last_payment_date_formatted: '',
//         custom_fields: [ [Object], [Object], [Object] ],
//         last_payment_date: '',
//         shipping_charge_tax_exemption_id: '',
//         lock_details: {},
//         place_of_supply_formatted: 'Andhra Pradesh',
//         current_sub_status_formatted: 'Draft',
//         tds_calculation_type: 'tds_item_level',
//         submitted_by_name: '',
//         created_by_id: '1155413000000015001',
//         is_backorder: '',
//         is_discount_before_tax: true,
//         attachment_name: '',
//         ach_payment_initiated: false,
//         last_reminder_sent_date: '',
//         payment_terms: 0,
//         shipping_charge_exclusive_of_tax: 0,
//         total: 2601,
//         tax_total_formatted: '₹396.66',
//         branch_id: '1155413000000062256',
//         reason_for_debit_note_formatted: 'Others',
//         branch_name: 'Head Office',
//         sub_total_formatted: '₹2,204.34',
//         tax_amount_withheld_formatted: '₹0.00',
//         bcy_shipping_charge: 0,
//         shipping_address: {
//           zip: '',
//           country: '',
//           address: '',
//           city: '',
//           phone: '',
//           street: '',
//           attention: '',
//           street2: '',
//           state: '',
//           fax: ''
//         },
//         shipping_charge_tax_formatted: '',
//         bcy_discount_total: 0,
//         orientation: 'portrait',
//         discount_applied_on_amount: 0,
//         due_date: '2024-03-23',
//         submitter_id: '',
//         submitted_by: '',
//         no_of_copies: 1,
//         payment_made_formatted: '₹0.00',
//         reverse_charge_tax_total: 0,
//         bcy_sub_total: 2204.34,
//         reminders_sent: 0,
//         salesperson_name: 'Sales 35',
//         filed_in_vat_return_type: '',
//         salesperson_id: '1155413000003598371',
//         payment_made: 0,
//         is_inventory_valuation_pending: false,
//         sub_total: 2204.34,
//         computation_type: 'basic',
//         shipping_charge_sac_code: '',
//         created_date: '2024-03-23',
//         invoice_url: 'https://zohosecurepay.in/books/katyayaniorganicsexports/secure?CInvoiceID=2-56a30cf8e6f4309e031cf984a7370b69afcc52b156360d335e0a7818c82650ac42443cab0482c8897a8b5392b2375a5df45ac39c930d57c89b15170f9522b7d1bf747bf136c83d3b ',
//         payment_reminder_enabled: true
//       }
//     }